### PR TITLE
11 fix dark mode

### LINKED ISSUE #11: Fix Dark mode

### PR DESCRIPTION
**Pull request by andreas-04**
fixed darkmode contrast using <cssvars> 
fixed padding using sx prop rather than inline style that didnt seem to be applying to root container
new sexy buttton

### CODE REVIEW

File: src/App.tsx [hunk 1]
```diff
@@ -130,7 +133,10 @@ function App() {
                   </Button>
                 ))}
               </Box>
-              {/* <Switch  checked={darkMode} onChange={() => setDarkMode(!darkMode)} /> */}
+              <IconButton onClick={() => setDarkMode(!darkMode)} >
+                <DarkModeIcon/>
+              </IconButton>
+               {/* <Switch  checked={darkMode} onChange={() => setDarkMode(!darkMode)} /> */}
```
Comment (JosephPBaruch) [inline src/App.tsx]: Comment can be removed

**Review by JosephPBaruch — COMMENTED** [review]
Looks good! Thanks for the doing this!

File: src/App.tsx (hunk 1 above)
Comment (JosephPBaruch) [reply src/App.tsx]: I went forward and completed this myself.

**Review by JosephPBaruch — APPROVED** [review]
Done.
